### PR TITLE
Fix Azure URL parsing

### LINKED ISSUE #443: az:// <container> not work as expected
**Describe the bug**
`az:// <container> / <blob> ` like uris (e.g. `az://testcontainer/ test.parquet` ) do not work as of version 0.12.3 at [pg_parquet](https://github.com/CrunchyData/pg_parquet) CI tests with azurite.

[This line change](https://github.com/apache/arrow-rs-object-store/pull/399/files#diff-5583e398a8deec11b274d9965eff8b5ade5226c7a020ca214a27d7d07dcc8a29R113) seems breaking the old behavior. 

**Before**
```sql
pg_parquet=# COPY (SELECT a FROM test) TO 'az://testcontainer/test.parquet' WITH (format 'parquet');
COPY 2
```

**After**
```sql
pg_parquet=# COPY (SELECT a FROM test) TO 'az://testcontainer/test.parquet' WITH (format 'parquet');
ERROR:  failed to finish parquet writer: External: Generic MicrosoftAzure error: Error performing PUT http://localhost:10000/devstoreaccount1/testcontainer in 9.424375ms - Server returned non-2xx status code: 400 Bad Request:
```

**Expected behavior**
It works as before in a similar way `azure://` prefix.

### PR DESCRIPTION
**Pull request by tustvold**
# Which issue does this PR close?

- Closes #443

# Rationale for this change
 

https://github.com/apache/arrow-rs-object-store/pull/399 introduced a breaking change to the way that we parse `az://` URLs. This IMO reflects a more sensible URL encoding, but this doesn't match the URL encoding expected by the rest of this crate, which in turn is borrowed from fsspec.

# What changes are included in this PR?

Reverts the URL parsing change in #399

# Are there any user-facing changes?

Technically this is a bug fix, but might make sense to wait for a breaking release.

### CODE REVIEW

File: src/parse.rs [hunk 1]
```diff
@@ -52,7 +52,7 @@ impl From<Error> for super::Error {
 /// - `memory:///` -> [`InMemory`]
 /// - `s3://bucket/path` -> [`AmazonS3`](crate::aws::AmazonS3) (also supports `s3a`)
 /// - `gs://bucket/path` -> [`GoogleCloudStorage`](crate::gcp::GoogleCloudStorage)
-/// - `az://account/container/path` -> [`MicrosoftAzure`](crate::azure::MicrosoftAzure) (also supports `adl`, `azure`, `abfs`, `abfss`)
+/// - `[az|abfs[s]]://container[@<account>.<host>]/path` -> [`MicrosoftAzure`](crate::azure::MicrosoftAzure)
```
Comment (tustvold) [inline src/parse.rs:55]: I opted to drop `azure` as it is a custom format AFAICT, and `adl` as it is deprecated by azure.

Whilst still supported for compatibility, people shouldn't be using them.

File: src/parse.rs [hunk 2]
```diff
@@ -299,11 +300,35 @@ mod tests {
                 (ObjectStoreScheme::MicrosoftAzure, "path"),
             ),
             (
-                "az://account/container",
-                (ObjectStoreScheme::MicrosoftAzure, ""),
+                "az://container/path",
+                (ObjectStoreScheme::MicrosoftAzure, "path"),
```
Comment (tustvold) [inline src/parse.rs:304]: This now matches https://docs.rs/object_store/0.12.4/object_store/azure/struct.MicrosoftAzureBuilder.html#method.with_url

File: src/parse.rs (hunk 1 above)
Comment (alamb) [reply src/parse.rs:55]: to be clear, you stopped documenting that `azure` is supported, but the code still supports it

File: src/parse.rs [hunk 3]
```diff
@@ -299,11 +300,35 @@ mod tests {
...
+            (
+                "abfss://container@account/path",
+                (ObjectStoreScheme::MicrosoftAzure, "path"),
+            ),
+            (
+                "adl://container/path",
+                (ObjectStoreScheme::MicrosoftAzure, "path"),
             ),
             (
-                "az://account/container/path",
```
Comment (alamb) [inline src/parse.rs:306]: Can we please keep this test so it is clearer what is the difference in behavior? I am not sure what this URL will parse to now

**Review by kylebarron — APPROVED** [review]
This seems fine to me; I apologize for the breakage

File: src/parse.rs (hunk 3 above)
Comment (tustvold) [reply src/parse.rs:306]: It is here https://github.com/apache/arrow-rs-object-store/pull/604#discussion_r2691944687

Just renamed
