### PR TITLE
Return Non-Generic Errors from HttpStore

### LINKED ISSUE #365: Error handling of HTTP storage backend not utilizing retry::RetryError::error when possible
**Describe the bug**
When using the HTTP/WebDAV storage backend many HTTP error statuses result in `crate::Error:Generic` making it harder to handle errors, especially compared to Azure/AWS/GCP backends which properly utilize `retry::RetryError::error`

**To Reproduce**
Use the HTTP storage backend, run a query that would result in a 304/401/403 response.

**Expected behavior**
Requests should return the relevant crate::Error based on the RetryError to easily handle the separate cases.

**Additional context**

PR available: #366

### PR DESCRIPTION
**Pull request by Rynoxx**
# Which issue does this PR close?

Closes #365.

# Rationale for this change

Allows for better error handling of HTTP statuses, and makes it consistent with how the S3/Azure/GCP clients handles RetryError.

# What changes are included in this PR?

Adjust implementation of `impl From<http::client::Error> for crate::Error` to use RetryError::error when possible.

# Are there any user-facing changes?

Most RetryError cases just returned `crate::Error::GenericError` before, now they'll return the crate::Error that matches the RetryError

### CODE REVIEW

File: src/http/client.rs [hunk 1]
```diff
@@ -275,7 +297,11 @@ impl Client {
                     source: Box::new(source),
                     path: path.to_string(),
                 },
-                _ => Error::Request { source }.into(),
+                _ => Error::Request {
```
Comment (tustvold) [inline src/http/client.rs:300]: I think we can now remove this match block entirely

Comment (Rynoxx) [reply src/http/client.rs]: Good point, cleaned that up

**Review by tustvold — APPROVED** [review]
