### PR TITLE
fix[prefix]: strip_meta from get_opts result in PrefixStore

### LINKED ISSUE #664: PrefixStore::head doesn't strip prefix from meta.location
**Describe the bug**

Calling `.head()` on a prefix store returns an ObjectMeta with a `.location` that contains the prefix. Other methods such as `.list()` strip the prefix: https://docs.rs/object_store/latest/src/object_store/prefix.rs.html#146

**To Reproduce**

```rust
let store = PrefixStore::new("client-jail", InMemory::new());
let path = Path::from("my-file");
match store.head(&path).await {
  Ok(meta) => {
    store.get(meta.location).await.expect("to not try open client-jail/client-jail/my-file");
  ...
```

**Expected behavior**

From prefix.rs, I think PrefixStore's `head()` method needs to call strip_meta.

**Current Workaround**
Reusing the path passed into `head()`.

Thank you ❤️

### PR DESCRIPTION
**Pull request by asubiotto**
PrefixStore was incorrectly not stripping the prefix from the returned result.

# Which issue does this PR close?

Closes #664
Closes #670

# Rationale for this change
 

Fix regression

# What changes are included in this PR?

Fix + assertion in integration tests + regression test

# Are there any user-facing changes?

### CODE REVIEW

**Comment by asubiotto** [comment]
cc @crepererum

File: src/prefix.rs [hunk 1]
```diff
@@ -299,6 +301,26 @@ mod tests {
         assert_eq!(&*read_data, data)
     }
 
+    // Regression test for
```
Comment (crepererum) [inline src/prefix.rs:304]: the extensions of the integration test is actually sufficient, but having an additional regression test also doesn't hurt.

**Review by crepererum — APPROVED** [review]
thank you

**Comment by asubiotto** [comment]
Thanks for the review! Can I/how do I request that this gets backported to 0.13?

**Comment by crepererum** [comment]
None of the breaking changes for 0.14.x have landed yet, so backporting is technically not even required. I will however note this in #672 so we don't forget.
